version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/packaging/docker/alpine"
      - "/packaging/docker/distroless"
      - "/packaging/debian"
      - "/packaging/rpm"
    schedule:
      interval: "monthly"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
