.\" Manpage for miniflux.
.TH "MINIFLUX" "1" "September 28, 2020" "\ \&" "\ \&"

.SH NAME
miniflux \- Minimalist and opinionated feed reader

.SH SYNOPSIS
\fBminiflux\fR [-vic] [-create-admin] [-debug] [-flush-sessions] [-info] [-migrate]
         [-reset-feed-errors] [-reset-password] [-version] [-config-file] [-config-dump]

.SH DESCRIPTION
\fBminiflux\fR is a minimalist and opinionated feed reader.

.SH OPTIONS
.PP
.B \-c
.RS 4
Load configuration file\&.
.RE
.PP
.B \-config-file
.RS 4
Load configuration file\&.
.RE
.PP
.B \-config-dump
.RS 4
Print parsed configuration values\&.
.RE
.PP
.B \-create-admin
.RS 4
Create admin user\&.
.RE
.PP
.B \-debug
.RS 4
Show debug logs\&.
.RE
.PP
.B \-flush-sessions
.RS 4
Flush all sessions (disconnect users)\&.
.RE
.PP
.B \-i
.RS 4
Show application information\&.
.RE
.PP
.B \-info
.RS 4
Show application information\&.
.RE
.PP
.B \-migrate
.RS 4
Run SQL migrations\&.
.RE
.PP
.B \-reset-feed-errors
.RS 4
Clear all feed errors for all users\&.
.RE
.PP
.B \-reset-password
.RS 4
Reset user password\&.
.RE
.PP
.B \-v
.RS 4
Show application version\&.
.RE
.PP
.B \-version
.RS 4
Show application version\&.
.RE

.SH CONFIGURATION FILE
The configuration file is a text file that follow these rules:
.LP
- Miniflux expects each line to be in KEY=VALUE format.
.br
- Lines beginning with # are processed as comments and ignored.
.br
- Blank lines are ignored.
.br
- There is no variable interpolation.
.PP
Keys are the same as the environment variables described below.
.br
Environment variables override the values defined in the config file.

.SH ENVIRONMENT
.TP
.B DEBUG
Set the value to 1 to enable debug logs\&.
.TP
.B LOG_DATE_TIME
Display the date and time in log messages\&.
.TP
.B WORKER_POOL_SIZE
Number of background workers (default is 5)\&.
.TP
.B POLLING_FREQUENCY
Refresh interval in minutes for feeds (default is 60 minutes)\&.
.TP
.B BATCH_SIZE
Number of feeds to send to the queue for each interval (default is 10)\&.
.TP
.B POLLING_SCHEDULER
Scheduler used for polling feeds. Possible values are "round_robin" (default) or "entry_frequency"\&.
.IP
The maximum number of feeds polled for a given period is subject to POLLING_FREQUENCY and BATCH_SIZE\&.
.IP
When "entry_frequency" is selected, the refresh interval for a given feed is equal to the average updating interval of the last week of the feed\&.
.IP
The actual number of feeds polled will not exceed the maximum number of feeds that could be polled for a given period\&.
.TP
.B SCHEDULER_ENTRY_FREQUENCY_MAX_INTERVAL
Maximum interval in minutes for the entry frequency scheduler (default is 24 hours)\&.
.TP
.B SCHEDULER_ENTRY_FREQUENCY_MIN_INTERVAL
Minimum interval in minutes for the entry frequency scheduler (default is 5 minutes)\&.
.TP
.B DATABASE_URL
Postgresql connection parameters\&.
.br
Default is "user=postgres password=postgres dbname=miniflux2 sslmode=disable"\&.
.TP
.B DATABASE_URL_FILE
Path to a secret key exposed as a file, it should contain $DATABASE_URL value\&.
.TP
.B DATABASE_MAX_CONNS
Maximum number of database connections (default is 20)\&.
.TP
.B DATABASE_MIN_CONNS
Minimum number of database connections (default is 1)\&.
.TP
.B LISTEN_ADDR
Address to listen on. Default is 127.0.0.1:8080\&.
.br
Use absolute path to listen on Unix socket (/var/run/miniflux.sock)\&.
.TP
.B PORT
Override LISTEN_ADDR to 0.0.0.0:$PORT\&.
.TP
.B BASE_URL
Base URL to generate HTML links and base path for cookies\&.
.br
Default is http://localhost/\&.
.TP
.B CLEANUP_FREQUENCY_HOURS
Cleanup job frequency. Remove old sessions and archive entries\&.
.br
Default is 24 hours\&.
.TP
.B CLEANUP_ARCHIVE_READ_DAYS
Number of days after marking read items as removed\&.
.br
Default is 60 days\&.
.TP
.B CLEANUP_ARCHIVE_UNREAD_DAYS
Number of days after marking unread items as removed\&.
.br
Default is 180 days\&.
.TP
.B CLEANUP_REMOVE_SESSIONS_DAYS
Number of days after removing old sessions from the database\&.
.br
Default is 30 days\&.
.TP
.B HTTPS
Forces cookies to use secure flag and send HSTS header\&.
.TP
.B DISABLE_HSTS
Disable HTTP Strict Transport Security header if \fBHTTPS\fR is set\&.
.TP
.B DISABLE_HTTP_SERVICE
Set the value to 1 to disable the HTTP service\&.
.TP
.B DISABLE_SCHEDULER_SERVICE
Set the value to 1 to disable the internal scheduler service\&.
.TP
.B CERT_FILE
Path to SSL certificate\&.
.TP
.B KEY_FILE
Path to SSL private key\&.
.TP
.B CERT_DOMAIN
Use Let's Encrypt to get automatically a certificate for this domain\&.
.TP
.B CERT_CACHE
Let's Encrypt cache directory (default is /tmp/cert_cache)\&.
.TP
.B METRICS_COLLECTOR
Set to 1 to enable metrics collector. Expose a /metrics endpoint for Prometheus.
.br
Disabled by default\&.
.TP
.B METRICS_REFRESH_INTERVAL
Refresh interval to collect database metrics\&. Default is 60 seconds\&.
.TP
.B METRICS_ALLOWED_NETWORKS
List of networks allowed to access the metrics endpoint (comma-separated values)\&.
.br
Default is 127.0.0.1/8\&.
.TP
.B OAUTH2_PROVIDER
OAuth2 provider to use\&. Only google is supported\&.
.TP
.B OAUTH2_CLIENT_ID
OAuth2 client ID\&.
.TP
.B OAUTH2_CLIENT_ID_FILE
Path to a secret key exposed as a file, it should contain $OAUTH2_CLIENT_ID value\&.
.TP
.B OAUTH2_CLIENT_SECRET
OAuth2 client secret\&.
.TP
.B OAUTH2_CLIENT_SECRET_FILE
Path to a secret key exposed as a file, it should contain $OAUTH2_CLIENT_SECRET value\&.
.TP
.B OAUTH2_REDIRECT_URL
OAuth2 redirect URL\&.
.TP
.B OAUTH2_OIDC_DISCOVERY_ENDPOINT
OpenID Connect discovery endpoint\&.
.TP
.B OAUTH2_USER_CREATION
Set to 1 to authorize OAuth2 user creation\&.
.TP
.B RUN_MIGRATIONS
Set to 1 to run database migrations\&.
.TP
.B CREATE_ADMIN
Set to 1 to create an admin user from environment variables\&.
.TP
.B ADMIN_USERNAME
Admin user login, used only if $CREATE_ADMIN is enabled\&.
.TP
.B ADMIN_USERNAME_FILE
Path to a secret key exposed as a file, it should contain $ADMIN_USERNAME value\&.
.TP
.B ADMIN_PASSWORD
Admin user password, used only if $CREATE_ADMIN is enabled\&.
.TP
.B ADMIN_PASSWORD_FILE
Path to a secret key exposed as a file, it should contain $ADMIN_PASSWORD value\&.
.TP
.B POCKET_CONSUMER_KEY
Pocket consumer API key for all users\&.
.TP
.B POCKET_CONSUMER_KEY_FILE
Path to a secret key exposed as a file, it should contain $POCKET_CONSUMER_KEY value\&.
.TP
.B PROXY_IMAGES
Avoids mixed content warnings for external images: http-only, all, or none\&.
.br
Default is http-only\&.
.TP
.B HTTP_CLIENT_TIMEOUT
Time limit in seconds before the HTTP client cancel the request\&.
.br
Default is 20 seconds\&.
.TP
.B HTTP_CLIENT_MAX_BODY_SIZE
Maximum body size for HTTP requests in Mebibyte (MiB)\&.
.br
Default is 15 MiB\&.
.TP
.B HTTP_CLIENT_PROXY
Proxy URL for HTTP client\&.
.br
Default is empty\&.
.TP
.B HTTP_CLIENT_USER_AGENT
The default User-Agent header to use for the HTTP client. Can be overridden in per-feed settings\&.
.br
Default is empty. When empty, Miniflux uses a default User-Agent that includes the Miniflux version\&.
.TP
.B AUTH_PROXY_HEADER
Proxy authentication HTTP header\&.
.TP
.B AUTH_PROXY_USER_CREATION
Set to 1 to create users based on proxy authentication information\&.
.TP
.B MAINTENANCE_MODE
Set to 1 to enable maintenance mode\&.
.TP
.B MAINTENANCE_MESSAGE
Define a custom maintenance message\&.

.SH AUTHORS
.P
Miniflux is written and maintained by Fr\['e]d\['e]ric Guillot\&.

.SH "COPYRIGHT"
.P
Miniflux is released under the Apache 2.0 license\&.
