// SPDX-FileCopyrightText: Copyright The Miniflux Authors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package timezone // import "miniflux.app/v2/internal/timezone"

import (
	"iter"
	"slices"
	"strings"
	"sync"
	"time"
)

var (
	tzCache = sync.Map{} // Cache for time locations to avoid loading them multiple times.
	tz      = map[string][]string{
		"Africa": {
			"Abidjan",
			"Accra",
			"Addis_Ababa",
			"Algiers",
			"Asmara",
			"Bamako",
			"Bangui",
			"Banjul",
			"Bissau",
			"Blantyre",
			"Brazzaville",
			"Bujumbura",
			"Cairo",
			"Casablanca",
			"Ceuta",
			"Conakry",
			"Dakar",
			"Dar_es_Salaam",
			"Djibouti",
			"Douala",
			"El_Aaiun",
			"Freetown",
			"Gaborone",
			"Harare",
			"Johannesburg",
			"Juba",
			"Kampala",
			"Khartoum",
			"Kigali",
			"Kinshasa",
			"Lagos",
			"Libreville",
			"Lome",
			"Luanda",
			"Lubumbashi",
			"Lusaka",
			"Malabo",
			"Maputo",
			"Maseru",
			"Mbabane",
			"Mogadishu",
			"Monrovia",
			"Nairobi",
			"Ndjamena",
			"Niamey",
			"Nouakchott",
			"Ouagadougou",
			"Porto-Novo",
			"Sao_Tome",
			"Timbuktu",
			"Tripoli",
			"Tunis",
			"Windhoek",
		},
		"America": {
			"Adak",
			"Anchorage",
			"Anguilla",
			"Antigua",
			"Araguaina",
			"Argentina/Buenos_Aires",
			"Argentina/Catamarca",
			"Argentina/Cordoba",
			"Argentina/Jujuy",
			"Argentina/La_Rioja",
			"Argentina/Mendoza",
			"Argentina/Rio_Gallegos",
			"Argentina/Salta",
			"Argentina/San_Juan",
			"Argentina/San_Luis",
			"Argentina/Tucuman",
			"Argentina/Ushuaia",
			"Aruba",
			"Asuncion",
			"Atikokan",
			"Atka",
			"Bahia",
			"Bahia_Banderas",
			"Barbados",
			"Belem",
			"Belize",
			"Blanc-Sablon",
			"Boa_Vista",
			"Bogota",
			"Boise",
			"Cambridge_Bay",
			"Campo_Grande",
			"Cancun",
			"Caracas",
			"Cayenne",
			"Cayman",
			"Chicago",
			"Chihuahua",
			"Ciudad_Juarez",
			"Coral_Harbour",
			"Costa_Rica",
			"Coyhaique",
			"Creston",
			"Cuiaba",
			"Curacao",
			"Danmarkshavn",
			"Dawson",
			"Dawson_Creek",
			"Denver",
			"Detroit",
			"Dominica",
			"Edmonton",
			"Eirunepe",
			"El_Salvador",
			"Ensenada",
			"Fortaleza",
			"Fort_Nelson",
			"Glace_Bay",
			"Goose_Bay",
			"Grand_Turk",
			"Grenada",
			"Guadeloupe",
			"Guatemala",
			"Guayaquil",
			"Guyana",
			"Halifax",
			"Havana",
			"Hermosillo",
			"Indiana/Indianapolis",
			"Indiana/Knox",
			"Indiana/Marengo",
			"Indiana/Petersburg",
			"Indiana/Tell_City",
			"Indiana/Vevay",
			"Indiana/Vincennes",
			"Indiana/Winamac",
			"Inuvik",
			"Iqaluit",
			"Jamaica",
			"Juneau",
			"Kentucky/Louisville",
			"Kentucky/Monticello",
			"Kralendijk",
			"La_Paz",
			"Lima",
			"Los_Angeles",
			"Lower_Princes",
			"Maceio",
			"Managua",
			"Manaus",
			"Marigot",
			"Martinique",
			"Matamoros",
			"Mazatlan",
			"Menominee",
			"Merida",
			"Metlakatla",
			"Mexico_City",
			"Miquelon",
			"Moncton",
			"Monterrey",
			"Montevideo",
			"Montreal",
			"Montserrat",
			"Nassau",
			"New_York",
			"Nipigon",
			"Nome",
			"Noronha",
			"North_Dakota/Beulah",
			"North_Dakota/Center",
			"North_Dakota/New_Salem",
			"Nuuk",
			"Ojinaga",
			"Panama",
			"Pangnirtung",
			"Paramaribo",
			"Phoenix",
			"Port-au-Prince",
			"Porto_Acre",
			"Port_of_Spain",
			"Porto_Velho",
			"Puerto_Rico",
			"Punta_Arenas",
			"Rainy_River",
			"Rankin_Inlet",
			"Recife",
			"Regina",
			"Resolute",
			"Rio_Branco",
			"Santa_Isabel",
			"Santarem",
			"Santiago",
			"Santo_Domingo",
			"Sao_Paulo",
			"Scoresbysund",
			"Shiprock",
			"Sitka",
			"St_Barthelemy",
			"St_Johns",
			"St_Kitts",
			"St_Lucia",
			"St_Thomas",
			"St_Vincent",
			"Swift_Current",
			"Tegucigalpa",
			"Thule",
			"Thunder_Bay",
			"Tijuana",
			"Toronto",
			"Tortola",
			"Vancouver",
			"Virgin",
			"Whitehorse",
			"Winnipeg",
			"Yakutat",
			"Yellowknife",
		},
		"Antartica": {
			"Casey",
			"Davis",
			"DumontDUrville",
			"Macquarie",
			"Mawson",
			"McMurdo",
			"Palmer",
			"Rothera",
			"Syowa",
			"Troll",
			"Vostok",
		},
		"Arctic": {"Longyearbyen"},
		"Asia": {
			"Aden",
			"Almaty",
			"Amman",
			"Anadyr",
			"Aqtau",
			"Aqtobe",
			"Ashgabat",
			"Atyrau",
			"Baghdad",
			"Bahrain",
			"Baku",
			"Bangkok",
			"Barnaul",
			"Beirut",
			"Bishkek",
			"Brunei",
			"Chita",
			"Chongqing",
			"Colombo",
			"Damascus",
			"Dhaka",
			"Dili",
			"Dubai",
			"Dushanbe",
			"Famagusta",
			"Gaza",
			"Harbin",
			"Hebron",
			"Ho_Chi_Minh",
			"Hong_Kong",
			"Hovd",
			"Irkutsk",
			"Istanbul",
			"Jakarta",
			"Jayapura",
			"Jerusalem",
			"Kabul",
			"Kamchatka",
			"Karachi",
			"Kashgar",
			"Kathmandu",
			"Khandyga",
			"Kolkata",
			"Krasnoyarsk",
			"Kuala_Lumpur",
			"Kuching",
			"Kuwait",
			"Macau",
			"Magadan",
			"Makassar",
			"Manila",
			"Muscat",
			"Nicosia",
			"Novokuznetsk",
			"Novosibirsk",
			"Omsk",
			"Oral",
			"Phnom_Penh",
			"Pontianak",
			"Pyongyang",
			"Qatar",
			"Qostanay",
			"Qyzylorda",
			"Riyadh",
			"Sakhalin",
			"Samarkand",
			"Seoul",
			"Shanghai",
			"Singapore",
			"Srednekolymsk",
			"Taipei",
			"Tashkent",
			"Tbilisi",
			"Tehran",
			"Tel_Aviv",
			"Thimphu",
			"Tokyo",
			"Tomsk",
			"Ulaanbaatar",
			"Urumqi",
			"Ust-Nera",
			"Vientiane",
			"Vladivostok",
			"Yakutsk",
			"Yangon",
			"Yekaterinburg",
			"Yerevan",
		},
		"Atlantic": {
			"Azores",
			"Bermuda",
			"Canary",
			"Cape_Verde",
			"Faroe",
			"Jan_Mayen",
			"Madeira",
			"Reykjavik",
			"South_Georgia",
			"Stanley",
			"St_Helena",
		},

		"Australia": {
			"Adelaide",
			"Brisbane",
			"Broken_Hill",
			"Canberra",
			"Currie",
			"Darwin",
			"Eucla",
			"Hobart",
			"Lindeman",
			"Lord_Howe",
			"Melbourne",
			"Perth",
			"Sydney",
			"Yancowinna",
		},
		"Europe": {
			"Amsterdam",
			"Andorra",
			"Astrakhan",
			"Athens",
			"Belfast",
			"Belgrade",
			"Berlin",
			"Bratislava",
			"Brussels",
			"Bucharest",
			"Budapest",
			"Busingen",
			"Chisinau",
			"Copenhagen",
			"Dublin",
			"Gibraltar",
			"Guernsey",
			"Helsinki",
			"Isle_of_Man",
			"Istanbul",
			"Jersey",
			"Kaliningrad",
			"Kirov",
			"Kyiv",
			"Lisbon",
			"Ljubljana",
			"London",
			"Luxembourg",
			"Madrid",
			"Malta",
			"Mariehamn",
			"Minsk",
			"Monaco",
			"Moscow",
			"Nicosia",
			"Oslo",
			"Paris",
			"Podgorica",
			"Prague",
			"Riga",
			"Rome",
			"Samara",
			"San_Marino",
			"Sarajevo",
			"Saratov",
			"Simferopol",
			"Skopje",
			"Sofia",
			"Stockholm",
			"Tallinn",
			"Tirane",
			"Tiraspol",
			"Ulyanovsk",
			"Vaduz",
			"Vatican",
			"Vienna",
			"Vilnius",
			"Volgograd",
			"Warsaw",
			"Zagreb",
			"Zurich",
		},
		"GMT": {},

		"Indian": {
			"Antananarivo",
			"Chagos",
			"Christmas",
			"Cocos",
			"Comoro",
			"Kerguelen",
			"Mahe",
			"Maldives",
			"Mauritius",
			"Mayotte",
			"Reunion",
		},
		"Pacific": {
			"Apia",
			"Auckland",
			"Bougainville",
			"Chatham",
			"Chuuk",
			"Easter",
			"Efate",
			"Fakaofo",
			"Fiji",
			"Funafuti",
			"Galapagos",
			"Gambier",
			"Guadalcanal",
			"Guam",
			"Honolulu",
			"Johnston",
			"Kanton",
			"Kiritimati",
			"Kosrae",
			"Kwajalein",
			"Majuro",
			"Marquesas",
			"Midway",
			"Nauru",
			"Niue",
			"Norfolk",
			"Noumea",
			"Pago_Pago",
			"Palau",
			"Pitcairn",
			"Pohnpei",
			"Port_Moresby",
			"Rarotonga",
			"Saipan",
			"Samoa",
			"Tahiti",
			"Tarawa",
			"Tongatapu",
			"Wake",
			"Wallis",
			"Yap",
		},
		"UTC": {},
	}
)

// Convert converts provided date time to actual timezone.
func Convert(tz string, t time.Time) time.Time {
	userTimezone := getLocation(tz)

	if t.Location().String() == "" {
		if t.Before(time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC)) {
			return time.Date(0, time.January, 1, 0, 0, 0, 0, userTimezone)
		}

		// In this case, the provided date is already converted to the user timezone by Postgres,
		// but the timezone information is not set in the time struct.
		// We cannot use time.In() because the date will be converted a second time.
		return time.Date(
			t.Year(),
			t.Month(),
			t.Day(),
			t.Hour(),
			t.Minute(),
			t.Second(),
			t.Nanosecond(),
			userTimezone,
		)
	} else if t.Location() != userTimezone {
		return t.In(userTimezone)
	}

	return t
}

// Now returns the current time with the given timezone.
func Now(tz string) time.Time {
	return time.Now().In(getLocation(tz))
}

func getLocation(tz string) *time.Location {
	if loc, ok := tzCache.Load(tz); ok {
		return loc.(*time.Location)
	}

	loc, err := time.LoadLocation(tz)
	if err != nil {
		loc = time.Local
	}

	tzCache.Store(tz, loc)
	return loc
}

func IsValid(timezone string) bool {
	continent, region, ok := strings.Cut(timezone, "/")
	if !ok {
		return false
	}
	regions, ok := tz[continent]
	if !ok {
		return false
	}
	if len(regions) == 0 {
		return true
	}
	return slices.Contains(regions, region)
}

// AvailableTimezones returns an iterator over supported timezones.
// This list is taken from Postgres on Debian Trixie.
func AvailableTimezones() iter.Seq[string] {
	return func(yield func(string) bool) {
		for continent, regions := range tz {
			if len(regions) == 0 {
				if !yield(continent) {
					return
				}
			} else {
				for _, region := range regions {
					if !yield(continent + "/" + region) {
						return
					}
				}
			}
		}
	}
}
