  - name: add Apt-key for influxeed-engine-repo
    become: yes
    apt_key:
      url: https://apt.influxeed-engine.app/KEY.gpg
      state: present

  - name: add influxeed-engine-repo
    become: yes
    apt_repository:
      repo: 'deb https://apt.influxeed-engine.app/ /' 
      state: present
      filename: influxeed-engine_repo
      update_cache: yes

  - name: install influxeed-engine
    become: yes
    apt:
      name: influxeed-engine
      state: present

  - name: add influxeed-engine linux_user
    become: yes
    user:
      name: "{{ influxeed-engine_linux_user }}"
      home: "/var/empty"
      create_home: "no"
      system: "yes"
      shell: "/bin/false"

  - name: create directory "/etc/influxeed-engine.d"
    become: yes
    file:
      path: /etc/influxeed-engine.d
      state: directory

  - name: copy influxeed-engine.conf
    become: yes
    template:
      src: "influxeed-engine.conf"
      dest: "/etc/influxeed-engine.conf"
    notify:
      - start_influxeed-engine.service
      - influxeed-engine_wait
