name: Build Binaries
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build_binaries.yml'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - '**.go'
jobs:
  build:
    name: Build
    if: github.repository_owner == 'miniflux'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Golang
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
          check-latest: true
      - name: Compile binaries
        env:
          CGO_ENABLED: 0
        run: make build
      - name: Upload binaries
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: binaries
          path: miniflux-*
          if-no-files-found: error
          retention-days: 5
