name: RPM Packages
permissions: read-all
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]
jobs:
  test-package:
    if: github.event.pull_request
    name: Test Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Build RPM Package
      run: make rpm
    - name: List generated files
      run: ls -l *.rpm
  publish-package:
    if: ${{ ! github.event.pull_request }}
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Build RPM Package
      run: make rpm
    - name: List generated files
      run: ls -l *.rpm
    - name: Upload package to repository
      env:
        FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      run: for f in *.rpm; do curl -F package=@$f https://$FURY_TOKEN@push.fury.io/miniflux/; done
